#pragma once

#include <iostream>
#include <random>
#include <windows.h>
#include <thread>
#include <atomic> 
#include <mutex>
#include <chrono>
//#include <string>
//#include <cctype>
//#include <array>
//#include <vector>
//#include <algorithm>
//#include <limits>
//#include <any>
//#include <stdexcept>
//#include <memory>
//#include <cstdio>
//#include <functional>
//#include <cmath>
//#include <cstdint>
//#include <iomanip>
//#include <conio.h>
//#include <cstdlib>