#pragma once
#include "color_enum.h"
#include "Utility.h"
#include "MyConsoleAPI.h"
#include "MyFunctions.h"
#include "Quize.h"
#include "NumberGenerator.h"
#include "NumberGuessingGame.h"
#include "CannaCalculator.h"